{% set name = "XStatic-jQuery" %}
{% set version = "3.7.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: f74dc463690611fe34e250953c144c56ae4ca17139e5f630378b4a988403c1e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - xstatic.pkg.jquery

about:
  home: https://jquery.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: jQuery javascript library packaged for setuptools

  description: |
    jQuery is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers.
  doc_url: https://jquery.com/
  dev_url: https://github.com/jquery/jquery

extra:
  recipe-maintainers:
    - ReimarBauer
