{% set name = "XStatic-jQuery" %}
{% set version = "3.5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0ae8f8ec5bbd28045ba4bca06767a38bd5fc27cf9b71f434589f59370dcd323

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - xstatic.pkg.jquery

about:
  home: https://jquery.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: jQuery javascript library packaged for setuptools

  description: |
    jQuery is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers.
  doc_url: https://jquery.com/
  dev_url: https://github.com/jquery/jquery

extra:
  recipe-maintainers:
    - ReimarBauer
